# dex-server: 추후 Github SSO 연동 시 사용
dex:
  enabled: false

configs:
  params:
    server.insecure: true
  repositories:
    gitops-helm-charts:
      url: https://github.com/dustjs159/gitops-helm-charts
      type: git
      name: gitops-helm-charts