## ArgoCD server
server:
  service:
    type: ClusterIP

## ApplicationSet controller (필수)
applicationSet:
  enabled: true

## Repo-server (GitHub App 쓰는 핵심 컴포넌트)
repoServer:
  replicas: 1

## Controller
controller:
  replicas: 1

## Dex / OAuth 아직 안 씀
dex:
  enabled: false

## Admin 계정 (로컬 테스트용)
configs:
  params:
    server.insecure: true