apiVersion: v1
kind: Service
metadata:
  name: {{ include "workloads-deployment.fullname" . }}
  labels:
    {{- include "workloads-deployment.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: {{ .Values.service.name | default "http" }}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
  selector:
    {{- include "workloads-deployment.selectorLabels" . | nindent 4 }}
